version: '3'

services:
  ew: 
    container_name: ew
    image: 718114245/ew:latest
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "1000k"
        max-file: "20"
    ports:
      - 30000:30000